// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/sociosarbis/grpc/boilerplate/proto"
)

// UserServiceClient is an autogenerated mock type for the UserServiceClient type
type UserServiceClient struct {
	mock.Mock
}

type UserServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceClient) EXPECT() *UserServiceClient_Expecter {
	return &UserServiceClient_Expecter{mock: &_m.Mock}
}

// UserDetail provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) UserDetail(ctx context.Context, in *proto.UserDetailReq, opts ...grpc.CallOption) (*proto.UserDetailRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.UserDetailRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UserDetailReq, ...grpc.CallOption) (*proto.UserDetailRes, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UserDetailReq, ...grpc.CallOption) *proto.UserDetailRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UserDetailRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UserDetailReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceClient_UserDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserDetail'
type UserServiceClient_UserDetail_Call struct {
	*mock.Call
}

// UserDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UserDetailReq
//   - opts ...grpc.CallOption
func (_e *UserServiceClient_Expecter) UserDetail(ctx interface{}, in interface{}, opts ...interface{}) *UserServiceClient_UserDetail_Call {
	return &UserServiceClient_UserDetail_Call{Call: _e.mock.On("UserDetail",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *UserServiceClient_UserDetail_Call) Run(run func(ctx context.Context, in *proto.UserDetailReq, opts ...grpc.CallOption)) *UserServiceClient_UserDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UserDetailReq), variadicArgs...)
	})
	return _c
}

func (_c *UserServiceClient_UserDetail_Call) Return(_a0 *proto.UserDetailRes, _a1 error) *UserServiceClient_UserDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceClient_UserDetail_Call) RunAndReturn(run func(context.Context, *proto.UserDetailReq, ...grpc.CallOption) (*proto.UserDetailRes, error)) *UserServiceClient_UserDetail_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUserServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserServiceClient creates a new instance of UserServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserServiceClient(t mockConstructorTestingTNewUserServiceClient) *UserServiceClient {
	mock := &UserServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
