services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --sql-mode="" --log-bin=/var/lib/mysql/binlog
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql-master.cnf:/etc/mysql/conf.d/binlog.cnf
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: grpc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

