version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --sql-mode="" --log-bin=/var/lib/mysql/binlog
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql-master.cnf:/etc/mysql/conf.d/binlog.cnf
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: grpc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
  canal:
    image: canal/canal-server:latest
    restart: unless-stopped
    volumes:
      - ./config/canal/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./config/canal/example/instance.properties:/home/admin/canal-server/conf/example/instance.properties
    ports:
      - "11111:11111"
    depends_on:
      - kafka
  zookeeper:
    image: bitnami/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    restart: unless-stopped
    volumes:
      - ./data/kafka:/bitnami/kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    - zookeeper

