// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/id.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IDServiceClient is the client API for IDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDServiceClient interface {
	IDGenerate(ctx context.Context, in *IDGenerateReq, opts ...grpc.CallOption) (*IDGenerateRes, error)
}

type iDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDServiceClient(cc grpc.ClientConnInterface) IDServiceClient {
	return &iDServiceClient{cc}
}

func (c *iDServiceClient) IDGenerate(ctx context.Context, in *IDGenerateReq, opts ...grpc.CallOption) (*IDGenerateRes, error) {
	out := new(IDGenerateRes)
	err := c.cc.Invoke(ctx, "/proto.IDService/IDGenerate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDServiceServer is the server API for IDService service.
// All implementations must embed UnimplementedIDServiceServer
// for forward compatibility
type IDServiceServer interface {
	IDGenerate(context.Context, *IDGenerateReq) (*IDGenerateRes, error)
	mustEmbedUnimplementedIDServiceServer()
}

// UnimplementedIDServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIDServiceServer struct {
}

func (UnimplementedIDServiceServer) IDGenerate(context.Context, *IDGenerateReq) (*IDGenerateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IDGenerate not implemented")
}
func (UnimplementedIDServiceServer) mustEmbedUnimplementedIDServiceServer() {}

// UnsafeIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDServiceServer will
// result in compilation errors.
type UnsafeIDServiceServer interface {
	mustEmbedUnimplementedIDServiceServer()
}

func RegisterIDServiceServer(s grpc.ServiceRegistrar, srv IDServiceServer) {
	s.RegisterService(&IDService_ServiceDesc, srv)
}

func _IDService_IDGenerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDGenerateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).IDGenerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IDService/IDGenerate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).IDGenerate(ctx, req.(*IDGenerateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IDService_ServiceDesc is the grpc.ServiceDesc for IDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IDService",
	HandlerType: (*IDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IDGenerate",
			Handler:    _IDService_IDGenerate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/id.proto",
}
